name: Terraform Deploy to Dev

on:
  push:
    branches:
      - main  # Runs only when changes are pushed to the "main" branch

  workflow_dispatch:  # Allows manual trigger in GitHub Actions

jobs:
  terraform:
    runs-on: ubuntu-latest
  
    permissions:
      id-token: write  # Required for OIDC
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: configure AWS Credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with: 
         role-to-assume: arn:aws:iam::954976304160:role/github-terraform-role
         aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: environments/dev

      - name: Terraform Plan
        run: terraform plan -var-file="dev.tfvars"
        working-directory: environments/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="dev.tfvars"
        working-directory: environments/dev
